def add_medical_disclaimer(text: str, language: str = "english") -> str:
    language = language.lower()

    disclaimers = {
        "english": (
            "\n\n⚠️ **Medical Disclaimer:**\n"
            "This report is generated by an AI system for informational and educational purposes only. "
            "It does not replace professional medical advice, diagnosis, or treatment. "
            "Always consult a qualified healthcare professional before making medical decisions."
        ),

        "hindi": (
            "\n\n⚠️ **महत्वपूर्ण अस्वीकरण:**\n"
            "यह रिपोर्ट केवल सूचना और शैक्षिक उद्देश्यों के लिए है। "
            "यह किसी भी प्रकार का चिकित्सीय निदान, उपचार या दवा का विकल्प नहीं है। "
            "कृपया किसी भी चिकित्सीय निर्णय से पहले योग्य डॉक्टर से परामर्श करें।"
        ),

        "hinglish": (
            "\n\n⚠️ **Important Disclaimer:**\n"
            "Yeh report sirf information aur education purpose ke liye hai. "
            "Yeh kisi bhi tarah ka medical diagnosis ya treatment nahi hai. "
            "Koi bhi medical decision lene se pehle qualified doctor se salah zaroor lein."
        ),

        "marathi": (
            "\n\n⚠️ **महत्वाची सूचना:**\n"
            "हा अहवाल केवळ माहिती व शैक्षणिक उद्देशांसाठी आहे. "
            "तो वैद्यकीय सल्ला, निदान किंवा उपचाराचा पर्याय नाही. "
            "कृपया कोणताही वैद्यकीय निर्णय घेण्यापूर्वी पात्र डॉक्टरांचा सल्ला घ्या."
        ),

        "tamil": (
            "\n\n⚠️ **முக்கிய அறிவிப்பு:**\n"
            "இந்த அறிக்கை தகவல் மற்றும் கல்வி நோக்கங்களுக்காக மட்டுமே உருவாக்கப்பட்டுள்ளது. "
            "இது மருத்துவ ஆலோசனை, நோயறிதல் அல்லது சிகிச்சைக்கு மாற்றாகாது. "
            "மருத்துவ முடிவுகளை எடுப்பதற்கு முன் தகுதியான மருத்துவரை அணுகவும்."
        ),

        "bhojpuri": (
            "\n\n⚠️ **जरूरी सूचना:**\n"
            "ई रिपोर्ट खाली जानकारी आ पढ़ाई खातिर बा। "
            "ई कौनो इलाज, दवाई, भा डॉक्टर के सलाह के जगह ना ले सकेला। "
            "कौनो भी मेडिकल फैसला लेवे से पहिले योग्य डॉक्टर से जरूर सलाह करीं।"
        )
    }

    disclaimer = disclaimers.get(language, disclaimers["english"])

    return text + disclaimer
